"""empty message

Revision ID: b44a49fe3b8d
Revises: 88e4ee7241bd
Create Date: 2023-04-05 22:34:35.751929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44a49fe3b8d'
down_revision = '88e4ee7241bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
